name: Run Selenium Scraper

on:
  schedule: 
    - cron: '0 15 * * *' # Runs every day at 15:00.
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write     
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true   # <-- NODIG voor pushen!
  
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager pytest

      - name: Run Python script to generate JSON
        run: |
          pip install -r requirements.txt || true
          python main.py
    
      - name: Commit JSON changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Voeg alleen gewijzigde bestanden toe
          git add circle8.json

          # Commit alleen als er iets veranderd is
          if ! git diff --cached --quiet; then
            git commit -m "Update JSON data [skip ci]"
            git push
          else
            echo "Geen veranderingen om te committen"
          fi
